# Generated by Django 5.2.17 on 2026-09-12 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKeyMaterial',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='phix_keys', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('kdf_algo', models.CharField(default='scrypt-n15-r8-p1', max_length=32)),
                ('kdf_salt', models.CharField(max_length=64)),
                ('key_wrap', models.TextField()),
                ('recovery_salt', models.CharField(max_length=64)),
                ('recovery_wrap', models.TextField()),
                ('key_check', models.TextField()),
                ('key_mode', models.CharField(default='password', max_length=16)),
                ('key_version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'phix_user_key_material',
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('device', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phix_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'phix_device_token',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('device', models.CharField(blank=True, default='', max_length=100)),
                ('payload', models.TextField(blank=True, default='')),
                ('size', models.PositiveIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phix_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'phix_sync_object',
            },
        ),
        migrations.CreateModel(
            name='SyncRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('payload', models.TextField(blank=True, default='')),
                ('size', models.PositiveIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('device', models.CharField(blank=True, default='', max_length=100)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.syncobject')),
            ],
            options={
                'db_table': 'phix_sync_revision',
                'ordering': ['-revision'],
            },
        ),
        migrations.AddIndex(
            model_name='syncobject',
            index=models.Index(fields=['user', 'updated_at'], name='phix_sync_o_user_id_33462c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='syncobject',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='syncrevision',
            unique_together={('object', 'revision')},
        ),
    ]
