# Generated by Django 5.2.17 on 2026-09-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkeymaterial',
            name='key_check_plain',
            field=models.CharField(default='', max_length=128),
        ),
    ]
