# Generated by Django 5.2.17 on 2026-09-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userkeymaterial_key_check_plain'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkeymaterial',
            name='auth_salt',
            field=models.CharField(default='', max_length=64),
        ),
    ]
