# Generated by Django 5.2.17 on 2026-09-12 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userkeymaterial_auth_salt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JtiBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(db_index=True, max_length=64, unique=True)),
                ('sid', models.PositiveIntegerField(db_index=True, default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'phix_jti_blacklist',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(blank=True, default='', max_length=100)),
                ('refresh_hash', models.CharField(max_length=256)),
                ('refresh_algo', models.CharField(default='pbkdf2_sha256', max_length=32)),
                ('refresh_salt', models.CharField(default='', max_length=64)),
                ('prev_refresh_hash', models.CharField(blank=True, default='', max_length=256)),
                ('prev_refresh_until', models.DateTimeField(blank=True, null=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('jkt', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_ip', models.CharField(blank=True, default='', max_length=64)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, default='', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phix_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'phix_token_session',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'revoked_at'], name='phix_token__user_id_2f78ca_idx')],
            },
        ),
    ]
