# Generated by Django 5.2.17 on 2026-09-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_p3_token_sessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokensession',
            name='refresh_salt',
        ),
        migrations.AlterField(
            model_name='tokensession',
            name='prev_refresh_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='tokensession',
            name='refresh_algo',
            field=models.CharField(default='sha256', max_length=32),
        ),
        migrations.AlterField(
            model_name='tokensession',
            name='refresh_hash',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
